### ISSUE TITLE
Terminal cannot use

### ISSUE THREAD

**Issue by Violin9906** [spaceneedle/Chromeduino#13]
the chrome console throws an error:
chrome.Event is not a constructor
It seems that chrome.Event has been removed from chrome.

**Comment by mrfrase3** [comment]
Hey @Violin9906,

Sorry about this, are you able to check what version of chromeduino your running? This was patched in version 2.0.2 (the latest).

Can you also confirm that you are running on ChromeOS?

I've got a feeling that Google is not sharing the update with everyone...

**Comment by mrfrase3** [comment]
nope. nevermind.

Just published 2.0.3 which should fix this issue.

Please let me know if this persists.

**Comment by saini391** [comment]
@mrfrase3 can you please help me in this project edu.codebender.cc actually after last update of chrome plugin some functionality is deprecated due to deprecation. Our chrome plugin is not working for edu.codebender.cc and not compiling AVR program in arduino. can you please check...

**Comment by mrfrase3** [comment]
Hey @saini391,

Firstly, this issue is probably not related.

Secondly, most of my time towards this at the moment is focused on this project which I do so for free. As you charge users for your product, I'm sure you can understand that I would charge for my time. If you wish to engage with me further, you can reach out to me privately, although I do not have a lot of spare time at the moment.

Otherwise, I wish you luck in finding the issue/solution.

**Comment by saini391** [comment]
Yes we can pay to you for this work. Can you give me your contact detail s.k.pe id, w.htspp no anything...

**Comment by Violin9906** [comment]
Thanks! The problem has been solved! Now it works very well on my chromebook. BTW, sorry about my so late reply----I seldom check my github account

**Comment by saini391** [comment]
Can you please help me how chrome latest version 75 work with edu.codebender.cc and block.codebender.cc
